# Generated by Django 4.1.4 on 2022-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textprocessor", "0002_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("bio", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="lorem", verbose_name="Active"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, help_text="lorem", verbose_name="Staff status"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="lorem",
                        verbose_name="Superuser status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
