# Generated by Django 4.1.4 on 2022-12-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textprocessor", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
