# Generated by Django 4.1.4 on 2022-12-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textprocessor", "0005_project_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="id",
        ),
        migrations.AddField(
            model_name="project",
            name="p_id",
            field=models.IntegerField(
                default=8, max_length=25, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
