# Generated by Django 4.1.4 on 2022-12-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textprocessor", "0008_alter_project_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="hosts",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="hosts",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="supe",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="message",
            name="blog",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.DeleteModel(
            name="Year",
        ),
        migrations.AlterField(
            model_name="department",
            name="dept",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="supervision",
            name="supervisor",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="tech",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="topics",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Machine",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
