# Generated by Django 4.1.4 on 2022-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textprocessor", "0009_remove_blog_hosts_remove_blog_topics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
